### ISSUE TITLE
Improved User Experience

### ISSUE THREAD

**Issue by joshking** [saucelabs/saucelabs-vusb-app#10]
As a user, I would like an improved user experience while using the vusb-app. This includes improved page layout, UI tweaks, and improved login experience. 

Figma preview:
https://t.co/eMDPDezK6N
(requires a free Figma account)

**Comment by wswebcreation** [comment]
Really  love the design @joshking 

1 question about the login page, how should the error look like if non matching user data is submitted?

**Comment by joshking** [comment]
I can get some error handling states in the designs for sure.

**Comment by wswebcreation** [comment]
Will be fixed by this https://github.com/saucelabs/saucelabs-vusb-app/releases/tag/v2.0.0-beta
