### ISSUE TITLE
Windows: vUSB jar command not working

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs/saucelabs-vusb-app#12]
## Expected Behavior
When the vUSB GUI is installed on a Windows machine in the `Program Files` folder it should be able to start the vUSB server

## Actual Behavior
It's not starting

## Steps to Reproduce the Problem

  1. Install it through `msiexec /i c:\packages\saucelabs\Sauce.Labs.vUSB.GUI.1.0.1.msi /QB ALLUSERS=1`
![image](https://user-images.githubusercontent.com/11979740/129533442-552f56be-25af-4537-89c7-42937d5aa71a.png)

**Comment by enriquegh** [comment]
@wswebcreation the issue here ended up being that the user had `ANDROID_HOME` and `JAVA_HOME` as environment variables but did not have those added onto `PATH`.

Should we add a check to `PATH` or print it like the other variables?

**Comment by wswebcreation** [comment]
Hi @enriquegh 

That's strange, if I look at my own version I see this

![image](https://user-images.githubusercontent.com/11979740/130016817-0c154fbe-5995-4664-ba6a-f48b656cc068.png)


I'll check if this is printed properly for Windows

**Comment by wswebcreation** [comment]
@enriquegh 

This is Windows

![image](https://user-images.githubusercontent.com/11979740/130019266-17c2a3e2-186b-47cf-a570-45c9ac0eb6e8.png)

What was the diff between the issue and what you saw in the GUI?

**Comment by enriquegh** [comment]
Hope these screenshots help @wswebcreation 

One is with JAVA_HOME set in my PATH env var the other one doesn't have it.
I use `java -version` to prove it's not on my PATH and therefore not accessible.

The TL;DR:

`JAVA_HOME` does not guarantee that the java executable is in PATH and available for the vUSB to use.
The fact that the server logs don't ever show an error saying that java is not a recognized command didn't help but that might just be more of a Node issue than an us issue.

![java-in-path](https://user-images.githubusercontent.com/6495540/130300443-4de970d0-b5c3-46b0-abc0-1d8cd97affaf.PNG)
![java-not-in-path](https://user-images.githubusercontent.com/6495540/130300447-d87d9ddd-10af-4acb-99b7-57ffcf50cdd0.PNG)

**Comment by wswebcreation** [comment]
Thanks, will check it and see if I can improve this behaviour in the GUI

**Comment by wswebcreation** [comment]
Hi @enriquegh 

I think I've fixed this now, see https://github.com/saucelabs/saucelabs-vusb-app/blob/1ce7cb730b8d2f3efd685c16b2c910fca51c8695/src/main/ipc/SystemChecks.ts#L37. I've also added the Java version as an extra information data point.
This **HAS NOT** been released in  https://github.com/saucelabs/saucelabs-vusb-app/releases/tag/v2.0.0-beta, but if you want you can build the PR from source.

**Error:**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/11979740/185334588-398c89ec-ac10-4634-a0a6-eb6d5b161c65.png">
**Version and path check**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/11979740/185336502-a2d1a11b-d454-4ce7-8658-2fdea4c56278.png">

Closing this for now, but please let me know if you have any other feedback
